### ISSUE TITLE
An error was found here

### ISSUE THREAD

**Issue by moeinkh88** [moeinkh88/benchmarking_FDE_Matlab_SciFracx#3]
https://github.com/JuliaTurkuDataScience/2022_Khalighi_FdeSolver/blob/b7dcf65d737e86a7e8220e5f77bde4053ed2860a/results/plot_figures.jl#L58

I got this error:
UndefVarError: easthetics not defined

**Comment by moeinkh88** [comment]
OK, it is a typo. It should be aesthetics.

But, there is another error:
https://github.com/JuliaTurkuDataScience/2022_Khalighi_FdeSolver/blob/b7dcf65d737e86a7e8220e5f77bde4053ed2860a/results/plot_figures.jl#L59


MethodError: Cannot `convert` an object of type Symbol to an object of type String
Closest candidates are:
  convert(::Type, !Matched::GeoInterface.AbstractGeometryTrait, !Matched::Any) at ~/.julia/packages/GeoInterface/J298z/src/fallbacks.jl:112
  convert(::Type{String}, !Matched::FilePathsBase.AbstractPath) at ~/.julia/packages/FilePathsBase/9kSEl/src/path.jl:117
  convert(::Type{String}, !Matched::WeakRefStrings.WeakRefString) at ~/.julia/packages/WeakRefStrings/31nkb/src/WeakRefStrings.jl:81
  ...

**Comment by RiboRings** [comment]
Oops, sorry! I mispelled "aesthetics". [This commit](https://github.com/JuliaTurkuDataScience/2022_Khalighi_FdeSolver/commit/51a7d9fc43a45978e2b52c7e2014819c9a7fa1c5) fixed the bug.

**Comment by moeinkh88** [comment]
Yes, but still the issue is open for this error:
> https://github.com/JuliaTurkuDataScience/2022_Khalighi_FdeSolver/blob/b7dcf65d737e86a7e8220e5f77bde4053ed2860a/results/plot_figures.jl#L59
> 
> MethodError: Cannot `convert` an object of type Symbol to an object of type String Closest candidates are: convert(::Type, !Matched::GeoInterface.AbstractGeometryTrait, !Matched::Any) at ~/.julia/packages/GeoInterface/J298z/src/fallbacks.jl:112 convert(::Type{String}, !Matched::FilePathsBase.AbstractPath) at ~/.julia/packages/FilePathsBase/9kSEl/src/path.jl:117 convert(::Type{String}, !Matched::WeakRefStrings.WeakRefString) at ~/.julia/packages/WeakRefStrings/31nkb/src/WeakRefStrings.jl:81 ...
